import {benchmarkReport} from './benchmark-report';
import type { GpuStat, Run, RunGpu, Sample } from '../src/types';
import { average, percentile } from './metrics';
import { combineStats, gpuMetricLabels, gpuMetricUnits, gpuMetrics } from '../src/gpu-stats';
import type { VisionState } from './vision';
// The confirmed effective state is recorded per model when its instance is loaded, so a
// row reports what LM Studio actually confirmed rather than only what was requested.
const visionOf=(run:Run,modelKey:string)=>(run.modelInfo[modelKey] as {vision?:VisionState}|undefined)?.vision;
export const visionRunNote=(run:Run)=>{const v=(run.environment as {vision?:{requested:string;note:string}}).vision;const states=run.config.modelKeys.map(k=>visionOf(run,k)).filter(Boolean) as VisionState[];return {requested:run.config.vision??v?.requested??'legacy/default',effective:[...new Set(states.map(s=>s.effective))].join(' | ')||'Not confirmed: no model was loaded for this run.',limitation:[...new Set(states.map(s=>s.limitation).filter(Boolean))].join(' ')||v?.note||''};};
export function summaries(run:Run){
 const groups=new Map<string,Sample[]>();for(const s of run.samples.filter(s=>!s.warmup)){const key=JSON.stringify([s.modelKey,s.testId,s.concurrency]);const list=groups.get(key)??[];list.push(s);groups.set(key,list);}
 return [...groups.values()].map(ss=>{const s=ss[0],ok=ss.filter(x=>x.status==='completed'),waves=run.waves.filter(w=>w.modelKey===s.modelKey&&w.testId===s.testId&&w.concurrency===s.concurrency);const gpu=combineStats(ss.map(x=>x.gpu));return {vision:run.config.vision??'legacy/default',visionEffective:visionOf(run,s.modelKey)?.effective??'Not confirmed',visionImagesSent:visionOf(run,s.modelKey)?.imagesSent??false,visionProjectorUnloaded:visionOf(run,s.modelKey)?.projectorUnloaded??false,visionLimitation:visionOf(run,s.modelKey)?.limitation??'',mtp:run.config.mtp??'legacy/default',mtpDraftTokens:run.config.mtp==='on'?(run.config.mtpDraftTokens??2):null,model:s.modelName,modelKey:s.modelKey,test:s.testName,testId:s.testId,concurrency:s.concurrency,requests:ss.length,failures:ss.length-ok.length,failureRate:(ss.length-ok.length)/ss.length,generationTps:average(ok.map(x=>x.metrics.generationTps)),estimatedPrefillTps:average(ok.map(x=>x.metrics.prefillTps)),throughput:average(waves.map(w=>w.throughput)),medianMs:percentile(ok.map(x=>x.metrics.durationMs),0.5),p95Ms:percentile(ok.map(x=>x.metrics.durationMs),0.95),ttftMs:average(ok.map(x=>x.metrics.ttftMs)),objective:average(ok.map(x=>x.objective.score)),localJudge:average(ok.map(x=>x.grades.filter(g=>g.source==='local').at(-1)?.score??null)),externalJudge:average(ok.map(x=>x.grades.filter(g=>g.source==='external').at(-1)?.score??null)),gpuHotSpotAvg:gpu?.tempHotSpot?.avg??null,gpuHotSpotMax:gpu?.tempHotSpot?.max??null,gpuCoreTempAvg:gpu?.tempCore?.avg??null,gpuCoreTempMax:gpu?.tempCore?.max??null,gpuMemoryTempMax:gpu?.tempMemory?.max??null,gpuPowerAvg:gpu?.power?.avg??null,gpuLoadAvg:gpu?.load?.avg??null,gpuReadings:gpu?.samples??0};});
}
const range=(s:GpuStat|null|undefined,unit:string,digits=1)=>!s?'Unavailable':`${s.min.toFixed(digits)}–${s.max.toFixed(digits)} ${unit} (average ${s.avg.toFixed(digits)})`;
export function gpuReport(gpu:RunGpu|undefined){
 if(!gpu)return 'GPU telemetry was not recorded for this run.';
 if(!gpu.available||!gpu.stats)return gpu.note||'GPU telemetry was not recorded for this run.';
 const stats=gpu.stats;
 return `Device: ${gpu.device}\n\nReadings: ${stats.samples}, sampled every ${gpu.intervalMs} ms.\n\n`+gpuMetrics.map(key=>`- ${gpuMetricLabels[key]}: ${range(stats[key],gpuMetricUnits[key])}`).join('\n')+`\n- Peak memory in use: ${stats.memoryUsedMax===null?'Unavailable':stats.memoryUsedMax.toFixed(0)+' MB'}\n\n${gpu.note}`;
}
function cell(v:unknown){let s=v===null||v===undefined?'':String(v);if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
export function exportText(run:Run,format:string){
 if(format==='json')return JSON.stringify(run,null,2);
 const rows=summaries(run);
 if(format==='csv'){const headers=rows.length?Object.keys(rows[0]):['model','test','concurrency','requests'];return '\uFEFF'+[headers.map(cell).join(','),...rows.map(row=>headers.map(k=>cell((row as any)[k])).join(','))].join('\r\n');}
 if(format!=='md')throw Error('Unsupported export format');
 const f=(n:number|null)=>n===null?'Unavailable':n.toFixed(2);
 return benchmarkReport(run)+`\n\n# ${run.config.name||'Local Model Bench'}\n\nCreated: ${run.created}\nStatus: ${run.status}\nVision requested: ${visionRunNote(run).requested}; confirmed effective state: ${visionRunNote(run).effective}${visionRunNote(run).limitation?'\n\nVision limitation: '+visionRunNote(run).limitation:''}\n\nNative MTP: ${run.config.mtp??'legacy/default'}; draft tokens: ${run.config.mtp==='on'?(run.config.mtpDraftTokens??2):'not applicable'}\n\nPrefill rates are estimates from client-timed processing events. Cache reuse is not measurable. Warm-ups are excluded. Generation includes reasoning tokens where reported by LM Studio.\n\n## Measurements\n\n`+rows.map(r=>`### ${r.model} / ${r.test} / concurrency ${r.concurrency}\n\nGeneration: ${f(r.generationTps)} tok/s; estimated prefill: ${f(r.estimatedPrefillTps)} tok/s; aggregate throughput: ${f(r.throughput)} tok/s. Median latency: ${f(r.medianMs)} ms; p95: ${f(r.p95Ms)} ms. Failures: ${r.failures}/${r.requests}.\n\nObjective: ${f(r.objective)}; local judge: ${f(r.localJudge)}; external judge: ${f(r.externalJudge)}.\n\nGPU hot spot: ${f(r.gpuHotSpotAvg)} °C average, ${f(r.gpuHotSpotMax)} °C peak; core ${f(r.gpuCoreTempAvg)} °C average; board power ${f(r.gpuPowerAvg)} W; from ${r.gpuReadings} reading(s) inside these requests.\n`).join('\n')+'\n## GPU thermals\n\n'+gpuReport(run.gpu)+'\n\n## Responses\n\n'+run.samples.filter(s=>!s.warmup).map(s=>`### ${s.modelName} — ${s.testName} (${s.id})\n\nStatus: ${s.status}${s.error?' — '+s.error:''}\n\n**Prompt**\n\n${s.prompt}\n\n**Response**\n\n${s.output}\n\n**Objective checks**\n\n${s.objective.checks.map(c=>`- ${c.passed?'PASS':'FAIL'}: ${c.label}: ${c.detail}`).join('\n')}\n\n${s.grades.map(g=>`**${g.source} grade (${g.judge}): ${g.score}**\n\n${g.summary}\n`).join('\n')}`).join('\n')+'\n## Run log\n\n'+run.logs.join('\n');
}
