import type { TestCase } from './types';

// Synthetic, fixed educational cases. Amounts are USD; no tax or unstated fees.
export const accountingCases = [
 {id:'cash-capital',name:'Owner investment and cash expense',task:'Record T1: owner invests $12,500 cash as owner capital. Record T2: pay $875 cash for rent used entirely this month.',answer:{T1:{Cash:{debit:12500,credit:0},OwnerCapital:{debit:0,credit:12500}},T2:{RentExpense:{debit:875,credit:0},Cash:{debit:0,credit:875}}},verification:'Investment: debit Cash and credit OwnerCapital 12,500. Current rent: debit RentExpense and credit Cash 875.'},
 {id:'receivable',name:'Credit sale and partial collection',task:'Record T1: provide $4,680 of services on account. Record T2: collect $1,725 of that receivable in cash. No other transactions or opening receivables.',answer:{T1:{AccountsReceivable:{debit:4680,credit:0},ServiceRevenue:{debit:0,credit:4680}},T2:{Cash:{debit:1725,credit:0},AccountsReceivable:{debit:0,credit:1725}}},verification:'Service revenue is earned when provided. Collection reduces receivables, not revenue. Ending receivable = 4,680 - 1,725 = 2,955.'},
 {id:'payable',name:'Equipment purchase and payable settlement',task:'Record T1: buy equipment for $9,450, paying $2,250 cash and owing the balance on account. Record T2: pay $1,800 cash toward that payable. Capitalize the equipment; do not record depreciation in this case.',answer:{T1:{Equipment:{debit:9450,credit:0},Cash:{debit:0,credit:2250},AccountsPayable:{debit:0,credit:7200}},T2:{AccountsPayable:{debit:1800,credit:0},Cash:{debit:0,credit:1800}}},verification:'Initial payable = 9,450 - 2,250 = 7,200. Remaining payable = 7,200 - 1,800 = 5,400.'},
 {id:'prepaid',name:'Prepaid insurance adjustment',task:'On October 1 a company pays $3,600 cash for 12 equal months of insurance starting that day, initially recording it as PrepaidInsurance. Record only T1: the October 31 adjustment for one fully expired month.',answer:{T1:{InsuranceExpense:{debit:300,credit:0},PrepaidInsurance:{debit:0,credit:300}}},verification:'One month = 3,600 / 12 = 300. Remaining prepaid = 3,300. Adjustment has no cash movement.'},
 {id:'accrual',name:'Accrued wages and later payment',task:'At month end, 3 employees have each worked 16 unpaid hours at $22.50/hour. Record T1: accrue these wages. Record T2: pay exactly those accrued wages next month. Ignore payroll taxes and deductions.',answer:{T1:{WagesExpense:{debit:1080,credit:0},WagesPayable:{debit:0,credit:1080}},T2:{WagesPayable:{debit:1080,credit:0},Cash:{debit:0,credit:1080}}},verification:'3 * 16 * 22.50 = 1,080. Next-month payment clears liability without a second expense.'},
 {id:'deferred',name:'Customer advance and earned revenue',task:'Record T1: receive $7,200 cash in advance for 6 equal months of service, initially as UnearnedRevenue. Record T2: recognize exactly 2 fully completed months of that service.',answer:{T1:{Cash:{debit:7200,credit:0},UnearnedRevenue:{debit:0,credit:7200}},T2:{UnearnedRevenue:{debit:2400,credit:0},ServiceRevenue:{debit:0,credit:2400}}},verification:'Monthly earned amount = 7,200 / 6 = 1,200; two months = 2,400; liability remaining = 4,800.'},
 {id:'depreciation',name:'Straight-line depreciation',task:'Equipment costs $26,400, has a $2,400 residual value, and a 5-year useful life. Use straight-line depreciation with 12 equal months per year. It has been in use for one full month. Record only T1: that month\'s depreciation using AccumulatedDepreciation, not a credit directly to Equipment.',answer:{T1:{DepreciationExpense:{debit:400,credit:0},AccumulatedDepreciation:{debit:0,credit:400}}},verification:'(26,400 - 2,400) / (5 * 12) = 400 per month.'},
 {id:'interest',name:'Interest accrual with a stated day count',task:'A $18,250 note payable bears 8% simple annual interest. Exactly 45 days of interest have accrued unpaid. Use actual/365: principal * annual rate * 45 / 365. Record only T1: interest accrual. Do not record principal.',answer:{T1:{InterestExpense:{debit:180,credit:0},InterestPayable:{debit:0,credit:180}}},verification:'18,250 * 8 / 100 * 45 / 365 = 180. No principal or cash changes.'},
 {id:'inventory',name:'Perpetual FIFO inventory sale',task:'A retailer uses perpetual FIFO inventory. Opening inventory is 40 units at $12 each. It then buys 30 units at $15 each on account. Record T1: that purchase. It then sells 50 units for $25 each in cash. Record T2: sale revenue and cash. Record T3: cost of goods sold and inventory reduction. No sales tax, returns, discounts, or freight.',answer:{T1:{Inventory:{debit:450,credit:0},AccountsPayable:{debit:0,credit:450}},T2:{Cash:{debit:1250,credit:0},SalesRevenue:{debit:0,credit:1250}},T3:{CostOfGoodsSold:{debit:630,credit:0},Inventory:{debit:0,credit:630}}},verification:'Purchase = 30 * 15 = 450. Sales = 50 * 25 = 1,250. FIFO cost = 40 * 12 + 10 * 15 = 630. Remaining inventory = 20 * 15 = 300.'},
 {id:'supplies',name:'Supplies adjustment',task:'Supplies has a $760 opening debit balance. During the month $1,140 of supplies purchases were already debited to Supplies. Physical supplies remaining at month end cost $425. Record only T1: the adjustment for supplies used.',answer:{T1:{SuppliesExpense:{debit:1475,credit:0},Supplies:{debit:0,credit:1475}}},verification:'Used = 760 + 1,140 - 425 = 1,475. Adjusted supplies = 425.'},
 {id:'bank',name:'Bank reconciliation calculations',task:'Bank statement ending balance is $8,420. Deposits in transit are $1,350 and outstanding checks are $975. Book cash before adjustment is $9,080. Bank-only items not yet in books: $25 service charge, $310 NSF customer check, and $50 interest earned. There are no other differences. Return adjusted_bank_cash and adjusted_book_cash.',answer:{adjusted_bank_cash:8795,adjusted_book_cash:8795},verification:'Bank: 8,420 + 1,350 - 975 = 8,795. Books: 9,080 - 25 - 310 + 50 = 8,795.'},
 {id:'month-end',name:'Mini month-end financial statements',task:'A new service business starts with zero balances. Owner invests $20,000 cash; buys $6,000 equipment for cash; buys $1,200 supplies on account; earns $8,000 services ($5,000 cash and $3,000 on account); collects $1,000 of that receivable; pays $1,200 rent expense and $2,000 wages expense in cash; pays $700 toward supplies payable; owner withdraws $500 cash (a drawing, not an expense). At month end supplies on hand are $300; record $100 depreciation and $400 unpaid wages. No other transactions, taxes, liabilities or expenses. Equipment is capitalized; supplies used are expensed. Return cash, accounts_receivable, supplies, equipment_net, accounts_payable, wages_payable, revenue, expenses, net_income, total_assets, total_liabilities, ending_equity. Equity includes capital plus income less drawings.',answer:{cash:15600,accounts_receivable:2000,supplies:300,equipment_net:5900,accounts_payable:500,wages_payable:400,revenue:8000,expenses:4600,net_income:3400,total_assets:23800,total_liabilities:900,ending_equity:22900},verification:'Cash = 20,000 - 6,000 + 5,000 + 1,000 - 1,200 - 2,000 - 700 - 500 = 15,600. AR = 3,000 - 1,000 = 2,000. Supplies used = 900. Expenses = 1,200 + 2,000 + 900 + 100 + 400 = 4,600. Income = 3,400. Assets = 15,600 + 2,000 + 300 + 5,900 = 23,800. Liabilities = 500 + 400 = 900. Equity = 20,000 + 3,400 - 500 = 22,900; assets = liabilities + equity.'},
];

export const accountingTests:TestCase[] = accountingCases.map(c=>{
 const journal='T1' in c.answer;
 const accounts=journal?[...new Set(Object.values(c.answer).flatMap(entry=>Object.keys(entry)))]:[];
 const format=journal?`Return a JSON object keyed by transaction ID (${Object.keys(c.answer).join(', ')}). Each transaction maps each affected account to {"debit": number, "credit": number}. Include both fields, with zero on the unused side. Use only affected accounts, once each per transaction. Allowed account names: ${accounts.join(', ')}. Keep transactions separate; do not net them together.`:`Return a JSON object with exactly these numeric keys: ${Object.keys(c.answer).join(', ')}.`;
 return {id:'accounting-'+c.id,name:c.name,category:'Accounting',version:1,kind:'quality',maxTokens:1536,
  prompt:`Basic accrual accounting exercise. All amounts are USD. Ignore taxes and any transactions not stated. Round final amounts to two decimal places when needed.\n\n${c.task}\n\n${format}\nReturn JSON only: no prose or code fences. Use JSON numbers, not currency strings. Key order is irrelevant. No extra keys.`,
  answerKey:JSON.stringify(c.answer),rubric:'Objective exact-answer exercise: correct accounts, debit/credit sides, amounts, and complete required output. Each case scores 100 only when all required content matches; otherwise 0. Key order and numeric formatting (300 vs 300.00) do not affect scoring. No points for prose or JSON validity alone. '+c.verification,
  rules:[{id:'accounting-answer',label:'All accounting values and entries correct',type:'json-equal',expected:JSON.stringify(c.answer),weight:1}]};
});
