import {useState} from 'react';
import {defaultComparisonFilter,type ComparisonFilter,type ModelProfile} from './model-profile';
import {useModalDialog} from './dialog';
type Props={profiles:Record<string,ModelProfile>;matching:string[];visible:string[];filter:ComparisonFilter;onChange:(f:ComparisonFilter)=>void;inspect:string;onInspect:(key:string)=>void;onSave:(key:string,p:ModelProfile)=>Promise<void>};
export function ComparisonControls({profiles,matching,visible,filter:f,onChange,onInspect,onSave}:Props){
 const [edit,setEdit]=useState('');
 const change=(patch:Partial<ComparisonFilter>)=>onChange({...f,...patch});
 return <section className="panel comparison-controls"><div className="section-heading"><div><h2>Compare models</h2><p className="hint">{visible.length} of {Object.keys(profiles).length} models shown · Filters apply to graphs, summaries, and responses.</p></div><button onClick={()=>onChange({...defaultComparisonFilter})}>Reset comparison</button></div>
 <div className="comparison-layout"><aside><label className="field"><span>Model type</span><select aria-label="Model type" value={f.kind} onChange={e=>change({kind:e.target.value as ComparisonFilter['kind'],basis:'totalB'})}><option value="all">Both + unknown</option><option value="dense">Dense</option><option value="moe">MoE</option><option value="unknown">Unknown type</option></select></label>
 {f.kind==='moe'&&<label className="field"><span>Parameter count to compare</span><select aria-label="Parameter basis" value={f.basis} onChange={e=>change({basis:e.target.value as ComparisonFilter['basis']})}><option value="totalB">Total parameters</option><option value="activeB">Active parameters</option></select></label>}
 <p className="hint">Unknown sizes are included in “All sizes” and excluded when a range is set. Unknown types are never assumed to be dense.</p></aside>
 <div><label className="field"><span>{f.kind==='moe'&&f.basis==='activeB'?'Active':'Total'} parameters (billions)</span><select aria-label="Parameter range" value={[':',':8','8:20','20:35','25:35','35:70','70:'].includes(f.min+':'+f.max)?f.min+':'+f.max:'custom'} onChange={e=>{if(e.target.value!=='custom'){const [min,max]=e.target.value.split(':');change({min,max});}}}><option value=":">All sizes</option><option value=":8">Up to 8B</option><option value="8:20">8–20B</option><option value="20:35">20–35B</option><option value="25:35">25–35B</option><option value="35:70">35–70B</option><option value="70:">70B and above</option><option value="custom">Custom range (edit below)</option></select></label>
 <div className="form-grid"><label className="field"><span>Minimum B</span><input aria-label="Minimum parameters" type="number" min="0" step="any" value={f.min} placeholder="No minimum" onChange={e=>change({min:e.target.value})}/></label><label className="field"><span>Maximum B</span><input aria-label="Maximum parameters" type="number" min="0" step="any" value={f.max} placeholder="No maximum" onChange={e=>change({max:e.target.value})}/></label></div>
 {f.min!==''&&f.max!==''&&+f.min>+f.max&&<p role="alert">Minimum must not exceed maximum.</p>}
 <label className="field"><span>Find a model</span><input aria-label="Search comparison models" value={f.search} placeholder="Model name or quantization…" onChange={e=>change({search:e.target.value})}/></label>
 <details open><summary>Matching models ({matching.length}) · choose which appear on the graphs</summary><div className="button-row"><button onClick={()=>change({excluded:f.excluded.filter(k=>!matching.includes(k))})}>Show matching</button><button onClick={()=>change({excluded:[...new Set([...f.excluded,...matching])]})}>Hide matching</button></div><div className="comparison-models">{matching.map(key=>{const p=profiles[key];return <div key={key}><label><input type="checkbox" aria-label={'Show '+key} checked={visible.includes(key)} onChange={()=>change({excluded:f.excluded.includes(key)?f.excluded.filter(k=>k!==key):[...f.excluded,key]})}/><span>{key}<small>{p.kind==='unknown'?'Unknown type':p.kind==='moe'?'MoE':'Dense'} · {p.totalB??'?'}B total{p.kind==='moe'?` · ${p.activeB??'?'}B active`:''}</small></span></label><button onClick={()=>onInspect(key)}>Inspect</button><button onClick={()=>setEdit(key)}>Edit metadata</button></div>;})}</div>{!matching.length&&<p>No models match. Change the range or reset the comparison.</p>}</details>
 </div></div>
 {edit&&<ProfileEditor key={edit} modelKey={edit} profile={profiles[edit]} onClose={()=>setEdit('')} onSave={p=>onSave(edit,p)}/>}
 </section>;
}
function ProfileEditor({modelKey,profile,onClose,onSave}:{modelKey:string;profile:ModelProfile;onClose:()=>void;onSave:(p:ModelProfile)=>Promise<void>}){
 const [kind,setKind]=useState(profile.kind),[total,setTotal]=useState(profile.totalB?.toString()??''),[active,setActive]=useState(profile.activeB?.toString()??''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const dialogRef=useModalDialog<HTMLElement>(onClose);
 return <div className="modal-backdrop"><section ref={dialogRef} tabIndex={-1} className="modal" role="dialog" aria-modal="true" aria-label="Model metadata"><div className="modal-header"><h2>Model metadata</h2><button onClick={onClose}>Close</button></div><div className="modal-body"><p>{modelKey}</p><p className="hint">Source: {profile.source}. Saved corrections apply to this exact model in all saved comparisons. Measurements remain unchanged.</p><label className="field"><span>Architecture type</span><select aria-label="Architecture type" value={kind} onChange={e=>setKind(e.target.value as ModelProfile['kind'])}><option value="unknown">Unknown</option><option value="dense">Dense</option><option value="moe">MoE</option></select></label><label className="field"><span>Total parameters (billions)</span><input aria-label="Total billions" type="number" step="any" min="0" value={total} onChange={e=>setTotal(e.target.value)}/></label>{kind==='moe'&&<label className="field"><span>Active parameters (billions)</span><input aria-label="Active billions" type="number" step="any" min="0" value={active} onChange={e=>setActive(e.target.value)}/></label>}{error&&<p role="alert">{error}</p>}</div><div className="modal-footer"><button disabled={saving} onClick={async()=>{setSaving(true);setError('');try{await onSave({kind,totalB:total===''?null:+total,activeB:kind!=='moe'||active===''?null:+active,source:'User supplied'});onClose();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}>Save model metadata</button></div></section></div>;
}
