import React,{useEffect,useState} from 'react';
import type {Run,RunConfig} from './types';
import {summaries} from '../electron/export';
import {performanceSummary} from './performance-summary';

const fmt=(v:number|null|undefined)=>v==null?'—':v.toLocaleString(undefined,{maximumFractionDigits:1});
export function LoadProfileControls({config:c,onChange,managed}:{config:RunConfig;onChange:(c:Partial<RunConfig>)=>void;managed:boolean}){
 const [targets,setTargets]=useState(c.contextSweep?.join(', ')??'');
 useEffect(()=>setTargets(c.contextSweep?.join(', ')??''),[c.contextSweep]);
 const parsed=targets.split(',').map(s=>Number(s.trim()));
 const valid=targets.trim()&&parsed.length<=8&&parsed.every(n=>Number.isInteger(n)&&n>=128&&n<=131072);
 const apply=()=>{if(valid)onChange({contextSweep:[...new Set(parsed)].sort((a,b)=>a-b)});};
 return <div className="load-profile">
  <div className="section-heading"><div><h3>Load pattern</h3><p className="hint">Use waves for a quick comparison or sustained load to find slowdowns over time.</p></div></div>
  <label className="field"><span>Load pattern</span><select aria-label="Load pattern" value={c.loadProfile??'waves'} onChange={e=>onChange({loadProfile:e.target.value as 'waves'|'sustained'|'arrival-rate',...(e.target.value!=='waves'?{mode:'performance',benchmark:undefined,vision:'off',cacheProtocol:c.cacheProtocol==='cached-prefix-followup'?'cold-prompt':c.cacheProtocol}:{})})}><option value="waves">Fixed request waves</option><option value="sustained">Sustained concurrency</option><option value="arrival-rate">Open-loop arrival rate</option></select></label>
  {c.loadProfile==='sustained'&&<><label className="field"><span>Seconds per combination</span><input aria-label="Seconds per combination" type="number" min={1} max={3600} value={c.durationSec??30} onChange={e=>{if(e.target.value)onChange({durationSec:Number(e.target.value)});}}/></label><p className="hint">Each model, prompt size, concurrency level and MTP depth gets this duration. Finished requests are replaced immediately. New requests stop at the deadline; remaining requests finish under their normal timeout. Throughput includes this drain time. A point stops at 10,000 requests or about 100 MB of saved prompt text.</p></>}
  {c.loadProfile==='arrival-rate'&&<><div className="form-grid"><label className="field"><span>Target arrivals per second</span><input aria-label="Target arrivals per second" type="number" min={0.01} max={10000} step={0.01} value={c.arrivalRatePerSecond??1} onChange={e=>{if(e.target.value)onChange({arrivalRatePerSecond:Number(e.target.value)});}}/></label><label className="field"><span>Response latency target (ms)</span><input aria-label="Response latency target (ms)" type="number" min={1} max={86400000} step={1} value={c.latencyTargetMs??1000} onChange={e=>{if(e.target.value)onChange({latencyTargetMs:Number(e.target.value)});}}/></label><label className="field"><span>Offer interval (seconds)</span><input aria-label="Offer interval (seconds)" type="number" min={1} max={3600} value={c.durationSec??30} onChange={e=>{if(e.target.value)onChange({durationSec:Number(e.target.value)});}}/></label></div><p className="hint">Requests are scheduled at the target arrival rate independently of response completion. If responses take longer than the arrival spacing, arrivals accumulate in a client queue and queue wait is reported; the client keeps queued arrivals instead of discarding them for capacity. The existing Concurrent requests setting is the finite in-flight cap. Achieved arrivals and target goodput are reported separately. The latency target applies to end-to-end response duration.</p></>}
  <label className="check"><input type="checkbox" checked={!!c.contextSweep?.length} onChange={e=>onChange({contextSweep:e.target.checked?[256,512,1024]:undefined,...(!e.target.checked&&c.cacheProtocol==='cached-prefix-followup'?{cacheProtocol:'cold-prompt'}:{}),...(e.target.checked?{mode:'performance',benchmark:undefined,vision:'off',performanceLengths:['short']}:{})})}/>Sweep input context sizes</label>
  {!!c.contextSweep?.length&&<><div className="form-grid"><label className="field"><span>Input adaptation tolerance (%)</span><input type="number" min="1" max="25" value={c.contextTolerancePct??5} onChange={e=>{if(e.target.value)onChange({contextTolerancePct:Number(e.target.value)});}}/><small>Up to three server-usage probes per target; probes are excluded from measured waves.</small></label><label className="field"><span>Cache protocol intent</span><select value={c.cacheProtocol??'cold-prompt'} onChange={e=>onChange({cacheProtocol:e.target.value as RunConfig['cacheProtocol']})}><option value="cold-prompt">Cold prompt (unique leading identifier)</option><option value="cached-prefix-followup">Cached-prefix follow-up (prime prefix, vary suffix)</option><option value="total-context">Total-context length</option></select></label>{c.cacheProtocol==='cached-prefix-followup'&&<label className="field"><span>Prefix target tokens</span><input type="number" min="64" max="32768" value={c.cachePrefixTokens??512} onChange={e=>{if(e.target.value)onChange({cachePrefixTokens:Number(e.target.value)});}}/></label>}</div><label className="field"><span>Approximate input token targets</span><input aria-label="Approximate input token targets" value={targets} onChange={e=>setTargets(e.target.value)} onBlur={apply} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();apply();}}}/><small>Targets: {c.contextSweep.join(', ')}. Adaptation uses up to three reported-usage probes; counts include endpoint chat formatting, and tokenizer support varies.</small></label>{!valid&&<p role="alert" className="hint amber">Enter valid whole-number targets. The last valid targets remain applied.</p>}{managed&&Math.max(...c.contextSweep)+c.maxTokens>c.contextLength&&<p role="alert" className="hint amber">The largest requested input plus output cap exceeds the configured per-slot context length ({c.contextLength} tokens). Lower the target or output cap, or raise the context length where supported.</p>}<p className="hint">Prompts are adapted against endpoint-reported input token counts when available; tolerance and final observed counts are saved. If usage is unavailable, the run keeps the rough four-characters-per-token prompt and labels adaptation unavailable. {c.cacheProtocol==='cached-prefix-followup'?'A separate prefix-only request primes the server before measured waves; measured suffixes vary after the exact preserved prefix. Cache hits remain unknown unless the endpoint reports them.':'Cache reuse can still occur and is not controlled by the client.'} {managed?'Set context length large enough for the largest input plus output.':'The endpoint owns context capacity; this app does not reconfigure it.'}</p></>}
 </div>;
}
export function LoadResults({run}:{run:Run}){
 const measured=run.samples.filter(s=>!s.warmup),timing=performanceSummary(measured),rows=summaries(run);
 if(!timing.streamingRequests&&!run.config.contextSweep?.length&&run.config.loadProfile!=='sustained'&&run.config.loadProfile!=='arrival-rate')return null;
 return <section className="panel"><h2>Streaming and load behavior</h2><p className="hint">First output is measured at this client, including network, server queueing and prompt processing. Stream gaps measure arriving chunks, which can contain multiple tokens. They are not exact inter-token latency.</p>
  <div className="table-scroll"><table><thead><tr><th>Model / prompt</th><th>Concurrency</th><th>Completed</th><th>Input target / actual mean</th><th>Cache protocol / accounting</th><th>Arrival starts/s / target goodput</th><th>First output p50 / p95 / p99 (ms)</th><th>Response p99 (ms)</th><th>Mean / worst stream gap (ms)</th><th>Estimated ms/token</th></tr></thead><tbody>{rows.map(r=><tr key={[r.modelKey,r.testId,r.concurrency,r.mtpDepth].join('|')}><td>{r.model}<small className="block">{r.test}{r.mtpDepth!==null?` · MTP depth ${r.mtpDepth}`:''}</small></td><td>{r.concurrency}</td><td>{r.requests-r.failures} / {r.requests}</td><td>{r.inputTargetTokens??'—'} / {fmt(r.actualInputTokensMean)}<small className="block">{r.inputToleranceObservedN?`${r.inputWithinTolerance}/${r.inputToleranceObservedN} within ${r.inputTargetTolerancePct}%`:''}</small></td><td>{r.cacheMode}<small className="block">cached tokens {r.cacheHitsKnown?fmt(r.cachedInputTokensMean):'unknown'}; prime usage {fmt(r.cachePrimeInputTokens)} (separate)</small></td><td>{r.arrivalAchievedPerSecond===null?'—':fmt(r.arrivalAchievedPerSecond)} / {r.arrivalGoodputPerSecond===null?'—':fmt(r.arrivalGoodputPerSecond)}{r.arrivalPlanned!==null&&<small className="block">{r.arrivalStarted}/{r.arrivalPlanned} started; {r.arrivalCancelledBeforeStart} cancelled</small>}</td><td>{fmt(r.firstEventP50Ms)} / {fmt(r.firstEventP95Ms)} / {fmt(r.firstEventP99Ms)}<small className="block">{r.streamingRequests} timed responses</small></td><td>{fmt(r.requestP99Ms)}</td><td>{fmt(r.meanStreamGapMs)} / {fmt(r.worstStreamGapMs)}</td><td>{fmt(r.estimatedTpotMs)}</td></tr>)}</tbody></table></div>
  <p className="hint">Percentiles use successful measured requests; warm-ups and failures are excluded. Failures remain in the completion count. Small samples make p95 and p99 unstable. Estimated ms/token divides the first-to-last output interval by reported output tokens minus one; buffering and hidden reasoning can affect it. Unavailable timings stay blank.</p>
  {run.config.loadProfile==='sustained'&&<p className="hint">Sustained concurrency: {run.config.durationSec??30} seconds of new requests per combination, followed by drain. This is a fixed-concurrency test, not a fixed-arrival-rate simulation. Each saved wave records its actual elapsed time and throughput.</p>}
  {run.config.loadProfile==='arrival-rate'&&<p className="hint">Open-loop offers: {run.config.arrivalRatePerSecond??1} arrivals/s for {run.config.durationSec??30}s; response target {run.config.latencyTargetMs??1000} ms. Achieved starts and goodput are reported separately. Goodput includes client queue wait and uses the full offer/drain interval. No overload drops are inferred; cancelled-before-start offers are reported separately.</p>}
 </section>;
}
